name: Build and release new GHCR packages
on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  LIT_VERSION: "3.10.2"
  LUVI_VERSION: "2.15.0.2"
  LUVIT_VERSION: "2.19.0-1"

jobs:
  runtime:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: lit
            image_name: lit
            version_tag: "3.10.2"
          - target: lit-git
            image_name: lit-git
            version_tag: "3.10.2"
          - target: luvi
            image_name: luvi
            version_tag: "2.15.0.2"
          - target: luvit
            image_name: luvit
            version_tag: "2.15.0.2"
          - target: all
            image_name: all
            version_tag: "2.15.0.2"
          - target: all-git
            image_name: all-git
            version_tag: "2.15.0.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Images
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.image_name }}
          tags: latest ${{ matrix.version_tag }}
          containerfiles: ./containers/lit-runtime/Dockerfile
          # layers: true
          oci: true
          extra-args: |
            --target=${{ matrix.target }}
          build-args: |
            LIT_VERSION=${{ env.LIT_VERSION }}
            LUVI_VERSION=${{ env.LUVI_VERSION }}
            LUVIT_VERSION=${{ env.LUVIT_VERSION }}

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  server:
    needs: runtime
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Lit
        run: |
          podman pull ${{ env.REGISTRY }}/lit:latest
      
      - name: Build Lit Image
        id: build-server
        uses: redhat-actions/buildah-build@v2
        with:
          image: lit-server
          tags: latest ${{ env.LIT_VERSION }}
          containerfiles: ./containers/lit-server/Dockerfile
          workdir: ./containers/lit-server
          # layers: true
          oci: true
          build-args: |
            LIT_VERSION=${{ env.LIT_VERSION }}
            LUVI_VERSION=${{ env.LUVI_VERSION }}
            LUVIT_VERSION=${{ env.LUVIT_VERSION }}

      - name: Push lit-server to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build-server.outputs.image }}
          tags: ${{ steps.build-server.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
